server:
  port: ${random.int[8080,9090]}
minio:
  # 服务地址
  endpoint: http://180.76.101.230:9000
  # 存储桶名称
  bucket: spring-boot-demo-minio
  # 用户名
  access-key: minioadmin
  # 密码
  secret-key: minioadmin

