spring:
  data:
    mongodb:
      host: 180.76.101.230
      port: 27017
      database: article_db
      username: mongoadmin
      password: secret
logging:
  level:
    org.springframework.data.mongodb.core: debug
