sftp:
  client:
    protocol: sftp
    host: 127.0.0.1
    port: "22"
    username: sftp
    password: sftp
    root: /home/sftp/
    sessionStrictHostKeyChecking: no
    sessionConnectTimeout: "15000"
    channelConnectedTimeout: "15000"
